language: php

php:
  - 7.2

env:
  - COMPOSER_MEMORY_LIMIT=-1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction --prefer-dist

script:
  - make test
