language: php

php:
  - 7.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-dist

script:
  - make test
