<?php

namespace FondOfSpryker\Zed\AvailabilityAlert\Persistence\Propel;

use Orm\Zed\AvailabilityAlert\Persistence\FosAvailabilityAlertSubscriptionQuery as BaseFosAvailabilityAlertSubscriptionQuery;

abstract class AbstractFosAvailabilityAlertSubscriptionQuery extends BaseFosAvailabilityAlertSubscriptionQuery
{
}
